language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer update --no-interaction

script:
    - composer lint

jobs:
  include:
    - name: 'Deploy'
      php: '7.2'
      if: branch = master
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./bin/deploy.sh; fi'

after_success:
    - travis_retry php vendor/bin/php-coveralls -v

notifications:
  slack:
    rooms:
      - literatom:BbJEUK17CJXUjbq7aZh2Q2q9#3jezy